import {
  ActionColumn,
  AggregateGroupColumn,
  AnnotateColumn,
  BooleanColumn,
  BoxPlotColumn,
  CategoricalColumn,
  CategoricalsColumn,
  DateColumn,
  GroupColumn,
  HierarchyColumn,
  ImpositionBoxPlotColumn,
  ImpositionCompositeColumn,
  LinkColumn,
  NestedColumn,
  NumberColumn,
  NumbersColumn,
  OrdinalColumn,
  RankColumn,
  ReduceColumn,
  ScriptColumn,
  SelectionColumn,
  SetColumn,
  StackColumn,
  StringColumn,
} from './';

/**
 * a map of all known column types
 */
export function models() {
  return {
    actions: ActionColumn,
    aggregate: AggregateGroupColumn,
    annotate: AnnotateColumn,
    boolean: BooleanColumn,
    boxplot: BoxPlotColumn,
    categorical: CategoricalColumn,
    categoricals: CategoricalsColumn,
    date: DateColumn,
    group: GroupColumn,
    hierarchy: HierarchyColumn,
    imposition: ImpositionCompositeColumn,
    impositionBoxPlot: ImpositionBoxPlotColumn,
    reduce: ReduceColumn,
    nested: NestedColumn,
    number: NumberColumn,
    numbers: NumbersColumn,
    ordinal: OrdinalColumn,
    rank: RankColumn,
    script: ScriptColumn,
    selection: SelectionColumn,
    set: SetColumn,
    stack: StackColumn,
    string: StringColumn,
    link: LinkColumn,
  };
}
